server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/tmpmgmt}

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: template-service
          uri: http://template-service:8081
          predicates:
            - Path=/api/v1/templates/**,/api/v1/template-drafts/**
        - id: clause-service
          uri: http://clause-service:8082
          predicates:
            - Path=/api/v1/clauses/**
        - id: questionnaire-service
          uri: http://questionnaire-service:8083
          predicates:
            - Path=/api/v1/questionnaires/**,/api/v1/questionnaire-sessions/**
        - id: assembly-service
          uri: http://assembly-service:8084
          predicates:
            - Path=/api/v1/assemblies/**
        - id: document-service
          uri: http://document-service:8086
          predicates:
            - Path=/api/v1/documents/**
        - id: admin-service
          uri: http://admin-service:8087
          predicates:
            - Path=/api/v1/users/**,/api/v1/roles/**
        - id: audit-service
          uri: http://audit-service:8088
          predicates:
            - Path=/api/v1/audit/**
        - id: search-service
          uri: http://search-service:8089
          predicates:
            - Path=/api/v1/search/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  pattern:
    level: "%5p [%X{correlationId:-}]"
